### ISSUE TITLE
Issue with Setting Up Example Directory in OpticalPooledScreens

### ISSUE THREAD

**Issue by hikiami** [feldman4/OpticalPooledScreens#22]
Hello,

I am currently facing an issue with setting up the example data in the OpticalPooledScreens repository. 
Although the example directory is created successfully, the sub-directory exampleC is not being created, which is hindering further analysis.
**The command I am using is:
python -m ops.paper.cell_idr setup_example example --ascp=ascp**

Everything seems to work fine until the script attempts to download. 
However, I encounter an error stating that a certain file or directory is missing. 
**The specific error message is as follows:
FileNotFoundError: [Errno 2] No such file or directory: 'example/experimentC/well_tile_list_example.csv'**
From this error, it appears that the example/experimentC directory is either not being created or is missing, which causes the script to fail when trying to access the well_tile_list_example.csv file.

I suspect there might have been changes to the file locations, or perhaps there is a bug in the script. 
Could you please provide some guidance on how to resolve this issue? 
If there's any more information or logs you need, I am happy to provide them.

Thank you for your assistance.

Best regards,
Hikiami

**Comment by Anivader** [comment]
Hi @hikiami,

Quick question, can this analysis be run without using "**_Aspera Command Line Interface (ascp)_**" ? I'm having issues installing it on my Mac. 

Specifically, when I run this -
`gem install aspera-cli
`
I get an error: "_You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory_"

Let me know.


Best
Ani

**Comment by hikiami** [comment]
Hi Ani,


Regarding the Aspera CLI installation issue on Mac, I found some useful instructions.

To download ascp, you generally need to:
1. Visit the IBM Aspera website. https://www.ibm.com/aspera/connect/
2, Download the Aspera Connect client suitable for Mac.
3. PATH if needed
export PATH=~/Applications/Aspera\ CLI/bin:$PATH    
export MANPATH=~/Applications/Aspera\ CLI/share/man:$MANPATH

Hopefully, this can help you bypass the permission issues associated with the Ruby gems installation.

As for my initial issue with OpticalPooledScreens, if ascp isn’t feasible, consider using FTP or HTTP for smaller datasets. However, for larger datasets, ascp is more efficient. I'm still seeking help regarding the missing 'example/experimentC' directory and the 'well_tile_list_example.csv' file, so any insights on this would be greatly appreciated.

Thank you for your support and looking forward to any further assistance you can provide.

Best,
Hikiami

**Comment by Anivader** [comment]
Thanks for the speedy response!
When I install, it shows up as "Aspera Connect" in my _Applications_ folder. In esport PATH=..., what should the PATH be ? 

As for your issue, I agree. Looks like the file is not being created.

**Comment by hikiami** [comment]
export PATH=/Users/XXXXXXX/Applications/Aspera\ CLI/bin:$PATH
export MANPATH=/Users/XXXXXXX/Applications/Aspera\ CLI/share/man:$MANPATH
Did this approach not work as expected? If you're encountering issues, it might be helpful to check if the path to Aspera CLI is correctly specified.

**Comment by Anivader** [comment]
Got this fixed somehow, didn't need to install the Aspera-client.

Re: your issue, _experimentC_ directory is not being created. Just replace line 38 of _ops/paper/cell_idr.py_ with the following - 
`os.makedirs("example/experimentC",exist_ok=True)`
This may change depending on your current path.

There are better ways to do this than explicit hard coding but if you just want this to work, go for it.

Hope it helps!
Ani

**Comment by feldman4** [comment]
Thanks for making an issue. Should be fixed now.
